"""Run the full perturbation-PLDS validation pipeline across many sessions.

For each session it:
  1. fits the PLDS at p=10 and caches everything -> session{N}/fit_p10.pkl
     (skipped if the cache already exists, so the job is resumable);
  2. runs the three-method validation (A off-manifold angle, B effective
     dimensionality, C counterfactual mechanism) -> validate_*.png;
  3. reproduces the old calcium off-plane *drive*-angle (Plot 2), with the
     onset-aligned, whole-trial and k-sweep variants -> validate_A_drive_*.png;
  4. writes per-session validate_report.md and drive_angle_report.md filled with
     that session's numbers; and appends a row to a top-level summary table.

Penalty is fixed at lam=1e-3 (not tuned) for cross-session comparability.

Run (long; ~12-15 min fit per session) in the background:
    /home/sp645/miniconda3/envs/ssm/bin/python run_all_sessions.py --sessions 1-7
"""

import argparse
import os
import time
import traceback

import fit_p10_cache as fitc
import run_manifold_analysis as mani
import run_taskA_drive_angle as drive

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    "perturbation_plds_results")


def _p(x):
    """Format a p-value compactly."""
    return f"{x:.2e}" if x < 1e-3 else f"{x:.3f}"


def write_validate_report(outdir, session, s):
    A, B, C = s["A"], s["B"], s["C"]
    lines = [
        f"# Validation of the perturbation PLDS latent — session {session} (p = {s['p']})",
        "",
        f"*Auto-generated by `run_all_sessions.py`. "
        f"Fit cached in `fit_p10.pkl`; figures `validate_A/B/C_*.png`.*",
        "",
        "## Setup",
        f"- **{s['n_pert'] + s['n_unp']} trials**: {s['n_pert']} perturbed, "
        f"{s['n_unp']} unperturbed; latent dim **p = {s['p']}**, lag J = {s['J']}.",
        f"- Unperturbed manifold dimension (90% var, train half): **k = {s['k']}**.",
        f"- Median perturbation onset (trimmed): bin {s['med_onset']}; "
        f"final ELBO {s['elbo']:,.0f}.",
        "",
        "## A. Off-manifold angle (perturbed leaves the unperturbed manifold)",
        "",
        "Angle of each latent state off the held-out unperturbed manifold "
        "(`arcsin(‖s⊥‖/‖s‖)`), onset-aligned.",
        "",
        "| comparison | angle | p |",
        "|---|---|---|",
        f"| perturbed, post-onset | {A['post']:.2f} ± {A['post_sd']:.2f}° | — |",
        f"| unperturbed (held-out) | {A['unp']:.2f} ± {A['unp_sd']:.2f}° | "
        f"perturbed>unpert: **{_p(A['p_pert_vs_unp'])}** |",
        f"| perturbed, pre-onset | {A['pre']:.2f} ± {A['pre_sd']:.2f}° | "
        f"post>pre: **{_p(A['p_post_vs_pre'])}** |",
        "",
        "![A](validate_A_angle.png)",
        "",
        "## B. Effective dimensionality (participation ratio)",
        "",
        "`PR = (Σλ)²/Σλ²` of the latent covariance, equal-N bootstrap (95% CI). "
        "Key contrast is pre- vs post-onset *within* perturbed trials.",
        "",
        "| condition | participation ratio (95% CI) |",
        "|---|---|",
        f"| unperturbed | {B['pr_unp'][0]:.2f} [{B['pr_unp'][1]:.2f}, {B['pr_unp'][2]:.2f}] |",
        f"| perturbed (whole trial) | {B['pr_pert'][0]:.2f} [{B['pr_pert'][1]:.2f}, {B['pr_pert'][2]:.2f}] |",
        f"| perturbed, **pre-onset** | {B['pr_pre'][0]:.2f} [{B['pr_pre'][1]:.2f}, {B['pr_pre'][2]:.2f}] |",
        f"| perturbed, **post-onset** | {B['pr_post'][0]:.2f} [{B['pr_post'][1]:.2f}, {B['pr_post'][2]:.2f}] |",
        "",
        f"Fraction of perturbed variance outside the {B['k']}-D manifold: "
        f"**{B['off_var']*100:.1f}%**.",
        "",
        "![B](validate_B_dim.png)",
        "",
        "## C. Mechanism — counterfactual (δG-on vs δG-off, kinematics fixed)",
        "",
        "| quantity | value |",
        "|---|---|",
        f"| ‖Δs‖ pre-onset | {C['dn_pre']:.3f} (≈0 by construction) |",
        f"| ‖Δs‖ post-onset | {C['dn_post']:.3f} |",
        f"| Δs off manifold (post) | {C['off_post']:.1f}% |",
        f"| realized δG drive off manifold | {C['dg_off']:.1f}% |",
        f"| participation ratio of Δs | {C['pr_delta']:.2f} |",
        "",
        "![C](validate_C_mechanism.png)",
        "",
        "> Onset alignment is essential: whole-trial averages dilute the effect; "
        "the dimensional expansion is transient and onset-locked.",
        "",
    ]
    with open(os.path.join(outdir, "validate_report.md"), "w") as f:
        f.write("\n".join(lines) + "\n")


def write_drive_report(outdir, session, s):
    al, wh, sw = s["aligned"], s["whole"], s["ksweep"]
    rows = "\n".join(
        f"| {K} | {v*100:.1f}% | {c:.1f}° | {p:.1f}° | {p-c:+.1f} |"
        for K, v, c, p in zip(sw["ks"], sw["var"], sw["control"], sw["perturbed"]))
    lines = [
        f"# Off-plane angle of the input drive (calcium Plot 2) — session {session}",
        "",
        f"*Auto-generated by `run_all_sessions.py`. Drive: control = G·z, "
        f"perturbed = G·z + u·δG·z; angle off plane = `90−arccos` = "
        f"`arcsin(‖v⊥‖/‖v‖)`. Manifold = trial-averaged unperturbed latent "
        f"trajectory, **k = {s['k']}** of p = {s['p']}.*",
        "",
        "## Onset-aligned (k = %d)" % s["k"],
        "",
        "| | drive angle off plane | p |",
        "|---|---|---|",
        f"| perturbed, post-onset | {al['post']:.2f} ± {al['post_sd']:.2f}° | — |",
        f"| control (G·z) | {al['ctrl']:.2f} ± {al['ctrl_sd']:.2f}° | "
        f"perturbed>control: **{_p(al['p_pert_vs_ctrl'])}** |",
        f"| perturbed, pre-onset | {al['pre']:.2f} ± {al['pre_sd']:.2f}° | "
        f"post>pre: **{_p(al['p_post_vs_pre'])}** |",
        "",
        "![onset-aligned](validate_A_drive_angle.png)",
        "",
        "## Whole trial — no onset alignment (closest to the old calcium plot)",
        "",
        "| | whole-trial drive angle off plane | p |",
        "|---|---|---|",
        f"| perturbed (G·z + u·δG·z) | {wh['pert']:.2f} ± {wh['pert_sd']:.2f}° | "
        f"perturbed>control: **{_p(wh['p_pert_vs_ctrl'])}** |",
        f"| control (G·z) | {wh['ctrl']:.2f} ± {wh['ctrl_sd']:.2f}° | |",
        "",
        "![whole trial](validate_A_drive_angle_wholetrial.png)",
        "",
        "Per-k whole-trial time courses:",
        "",
        "![whole trial k-sweep](validate_A_drive_angle_wholetrial_ksweep.png)",
        "",
        "## Robustness to manifold dimension k (whole trial)",
        "",
        "| k | manifold var% | control | perturbed | gap |",
        "|---|---|---|---|---|",
        rows,
        "",
        "![k sweep](validate_A_drive_angle_ksweep.png)",
        "",
        "> The control baseline shrinks as k grows (the manifold absorbs more of "
        "the G·z drive), but the perturbed>control gap persists across k. The gap "
        "mixes the δG effect with kinematic trial-group differences; see "
        "`validate_report.md` Test C for the δG-isolating counterfactual.",
        "",
    ]
    with open(os.path.join(outdir, "drive_angle_report.md"), "w") as f:
        f.write("\n".join(lines) + "\n")


def parse_sessions(spec):
    out = []
    for part in spec.split(","):
        part = part.strip()
        if "-" in part:
            a, b = part.split("-")
            out.extend(range(int(a), int(b) + 1))
        elif part:
            out.append(int(part))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sessions", type=str, default="1-7",
                    help="e.g. '1-7' or '1,3,5'")
    ap.add_argument("--refit", action="store_true",
                    help="refit even if fit_p10.pkl already exists")
    args = ap.parse_args()
    sessions = parse_sessions(args.sessions)
    print(f"=== run_all_sessions: sessions {sessions} ===", flush=True)

    summary = []  # (session, ok, note)
    for sess in sessions:
        t0 = time.time()
        outdir = os.path.join(ROOT, f"session{sess}")
        os.makedirs(outdir, exist_ok=True)
        cache_path = os.path.join(outdir, "fit_p10.pkl")
        print(f"\n########## SESSION {sess} ##########", flush=True)
        try:
            if args.refit or not os.path.exists(cache_path):
                fitc.fit_and_cache(sess, cache_path)
            else:
                print(f"[s{sess}] cache exists, skipping fit", flush=True)

            mstats = mani.run(cache_path, outdir)
            write_validate_report(outdir, sess, mstats)

            dstats = drive.run(cache_path, outdir)
            write_drive_report(outdir, sess, dstats)

            note = (f"p={mstats['p']} k={mstats['k']} "
                    f"A:{mstats['A']['post']:.1f}/{mstats['A']['unp']:.1f}° "
                    f"drive:{dstats['whole']['pert']:.1f}/{dstats['whole']['ctrl']:.1f}°")
            summary.append((sess, True, note))
            print(f"[s{sess}] DONE in {(time.time()-t0)/60:.1f} min — {note}", flush=True)
        except Exception as e:
            tb = traceback.format_exc()
            summary.append((sess, False, str(e)))
            print(f"[s{sess}] FAILED: {e}\n{tb}", flush=True)

    # top-level summary
    lines = ["# Multi-session run summary", "",
             f"*Generated {time.strftime('%Y-%m-%d %H:%M')} by `run_all_sessions.py`.*", "",
             "| session | status | notes |", "|---|---|---|"]
    for sess, ok, note in summary:
        lines.append(f"| {sess} | {'ok' if ok else 'FAILED'} | {note} |")
    with open(os.path.join(ROOT, "all_sessions_summary.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\n=== summary written to {ROOT}/all_sessions_summary.md ===", flush=True)


if __name__ == "__main__":
    main()
